- name: Build Docker Image
  hosts: dockerservers
  gather_facts: false
  remote_user: root  # Changed from root to jenkins
  tasks:
    - name: Building Docker Image
      docker_image:
         name: omegalul:latest
         source: build
         build:
            path: ~/66026190  # Updated to match the corrected folder structure
         state: present
         force_source: true
